theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  install.md
  
site_name: SmartGreenhouse

repo_url: "https://team12-uofg.github.io/SmartGreenhouse/"
site_favicon: neptune.ico
copyright: "SmartGreenhouse is licensed under the <a href='https://github.com/Team12-UofG/SmartGreenhouse/blob/master/LICENSE.txt'> GNU General Public License</a><br>."


pages:
    - Home: index.md
    - Project Overview:
        - About Us: beforeyoustart.md
        - System Overview: stystemoverview.md
    - Install:
        - Hardware: install-hw.md
        - Software: install-sw.md
    - FAQ:
        - FAQ.md
    - MySmartGreenhouse:
        - MySmartGreenhouse.md
