site_name: SmartGreenhouse

copyright: "SmartGreenhouse is licensed under the <a href='https://github.com/Team12-UofG/SmartGreenhouse/blob/master/LICENSE.txt'> GNU General Public License</a><br>."


pages:
    - Home: index.md
    - Project Overview:
        - About Us: beforeyoustart.html
        - System Overview: systemoverview.md
    - Install:
        - Hardware: install-hw.md
        - Software: install-sw.md
    - FAQ:
        - FAQ.md
    - MySmartGreenhouse:
        - mysmartgreenhouse.md
